# Generated by Django 5.0.2 on 2024-02-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('person_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person_catalog.person')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
            ],
            bases=('person_catalog.person',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=2000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('publication_date', models.DateField()),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=255)),
                ('saga', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(max_length=255, to='book_catalog.author')),
                ('genre', models.ManyToManyField(blank=True, null=True, to='core.genre')),
                ('language', models.ManyToManyField(max_length=100, to='core.language')),
            ],
        ),
    ]
