# Generated by Django 4.2.9 on 2024-07-18 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book_catalog", "0002_alter_book_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookstate",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e", "Empty"),
                    ("r", "Read"),
                    ("t", "To read"),
                    ("i", "Reading"),
                ],
                default="e",
                help_text="Estado actual del libro",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="bookstate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
