# Generated by Django 5.0.4 on 2024-05-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0002_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author']},
        ),
    ]
