# Generated by Django 4.2.9 on 2024-07-18 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book_catalog", "0003_bookstate_status_bookstate_user"),
    ]

    operations = [
        migrations.RenameModel(old_name="BookState", new_name="UserBookRelation",),
    ]
