# Generated by Django 4.2.9 on 2024-07-20 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book_catalog", "0004_rename_bookstate_userbookrelation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrelation",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book_catalog.book"
            ),
        ),
        migrations.AlterField(
            model_name="userbookrelation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userbookrelation",
            name="status",
            field=models.CharField(
                choices=[("r", "Read"), ("t", "To read"), ("i", "Reading")],
                help_text="Estado actual del libro",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="userbookrelation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbookrelation", unique_together={("user", "book")},
        ),
    ]
