# Generated by Django 4.2.9 on 2024-07-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0005_alter_userbookrelation_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                help_text="Enter a book genre (e.g. Science Fiction,French Poetry etc.)",
                max_length=200,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="book", unique_together={("title", "author")},
        ),
        migrations.AlterUniqueTogether(
            name="booksaga", unique_together={("name", "author")},
        ),
    ]
