# Generated by Django 4.2.9 on 2024-07-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0006_book_cover_image_alter_genre_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookrelation",
            name="read_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userbookrelation",
            name="reading_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                help_text="Inserte el título del libro.", max_length=200
            ),
        ),
    ]
