# Generated by Django 4.2.9 on 2024-07-26 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0007_userbookrelation_read_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookrelation",
            name="rate",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userbookrelation",
            name="review",
            field=models.TextField(
                blank=True,
                help_text="Enter a brief review of the book",
                max_length=1000,
                null=True,
            ),
        ),
    ]
