# Generated by Django 4.2.9 on 2024-07-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0008_userbookrelation_rate_userbookrelation_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rate_mean",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="book_catalog.genre"),
        ),
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="book", name="title", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="booksaga", name="name", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="userbookrelation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("r", "Read"), ("t", "To read"), ("i", "Reading")],
                max_length=1,
                null=True,
            ),
        ),
    ]
