# Generated by Django 4.2.9 on 2024-07-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "book_catalog",
            "0009_book_rate_mean_alter_book_genre_alter_book_summary_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookrelation",
            name="total_of_rates",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userbookrelation",
            name="total_of_reviews",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
