# Generated by Django 4.2.9 on 2024-07-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0010_userbookrelation_total_of_rates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbookrelation",
            name="total_of_reviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
