# Generated by Django 4.2.9 on 2024-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0012_alter_userbookrelation_total_of_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_of_rates",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="total_of_reviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
