# Generated by Django 4.2.9 on 2024-07-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0013_book_total_of_rates_book_total_of_reviews"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="rate_mean",),
        migrations.RemoveField(model_name="book", name="total_of_rates",),
        migrations.RemoveField(model_name="book", name="total_of_reviews",),
        migrations.RemoveField(model_name="userbookrelation", name="rate",),
        migrations.RemoveField(model_name="userbookrelation", name="total_of_rates",),
        migrations.RemoveField(model_name="userbookrelation", name="total_of_reviews",),
        migrations.AddField(
            model_name="userbookrelation",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userbookrelation",
            name="review",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
