# Generated by Django 4.2.9 on 2024-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "book_catalog",
            "0014_remove_book_rate_mean_remove_book_total_of_rates_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookrelation",
            name="review_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
