# Generated by Django 4.2.9 on 2024-07-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0015_userbookrelation_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="authors/"),
        ),
    ]
