# Generated by Django 4.2.9 on 2024-07-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0016_author_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="biography",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="social_media",
            field=models.URLField(blank=True, null=True),
        ),
    ]
