# Generated by Django 4.2.9 on 2024-07-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0018_booksaga_description_alter_book_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                blank=True, null=True, to="book_catalog.genre"
            ),
        ),
    ]
