# Generated by Django 4.2.9 on 2024-07-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_catalog", "0019_alter_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="book_catalog.genre"),
        ),
    ]
